image:
  file: .gitpod.Dockerfile
tasks:
  - name: Install Rails
    init: bundle install && rails db:setup && rails runner scripts/create_data.rb
  - name: Install Claude Code
    init: npm install -g @anthropic-ai/claude-code
  - name: Install ChatGPT Codex
    init: npm install -g @openai/codex
  - name: Update node
    init: |
      nvm install 22
      node -v # Should print "v22.16.0".
vscode:
  extensions:
    - vortizhe.simple-ruby-erb
